common/history/buildings/01_settler_coast.txt

patched lack of urban buildings across multiple states in settler's coast

brick-through-windshield.txt

---

common/building_groups/exether_building_groups.txt
common/history/buildings/01_settler_coast.txt
common/production_methods/exether_misc.txt
localization/replace/english/exether_production_methods_l_english.yml

unfucking-magic-industries

---

map_data/state_regions/05_locari.txt

I forgot to tell them they had a new name so they visited the void, but I found them and now they're back

The fish are back

---

common/country_definitions/05_locari.txt

Changed from Cult of Man (default) to Cult of the Sun as per lore discussions

SSC Religion Change

---

common/history/buildings/01_settler_coast.txt

resurrecting Darvak

---

common/country_definitions/05_locari.txt
common/cultures/00_human.txt
common/discrimination_traits/exether_cultural_descriptive.txt
common/history/pops/05_locari.txt
common/history/states/05_locari.txt
localization/replace/english/exether_culture_traits_l_english.yml
localization/replace/english/exether_cultures_l_english.yml

And all that fun stuff that entails

Vystemian culture added

---

map_data/state_regions/00_noricum.txt
map_data/state_regions/01_settlers_coast.txt
map_data/state_regions/02_central_zalaron.txt
map_data/state_regions/04_west_zalaron.txt
map_data/state_regions/06_northwestern_islands.txt

Noricum about done. Needs to be tested when the mod is more playable to see if it's enough supply for the continent.

Noricum Updated

---

common/history/buildings/08_south_seas.txt

Building file was closed early
Gave Amanzi enough industry to fix their shortages Fixed various missing levels, especially for ports.

Changed: Nobody has buildings -> People have buildings

---

gui/country_panel.gui
localization/replace/english/exether_interfaces_l_english.yml

simple change to the gui to hide the modifier on the country panel, overwrites some vanilla stuff buts is total overhaul anyway so w/e

hide modifier for arcana surplus on country_panel

---

common/buildings/exether_raw_resources.txt
common/production_method_groups/exether_raw_resources.txt
common/production_methods/exether_raw_resources.txt

Changed Leviathan Outposts to actually have inputs that matter Toned down the amount of blood sacrifice needed to obtain blubber Added PMs to sacrifice even fewer laborers.

Dudes Rock (themselves into a wet grave)

---

common/flag_definitions/flag_definitions_settler_coast.txt
common/scripted_triggers/00_clothes_triggers.txt

Fixed an endless looping error check

That's not a country, this is a country

---

common/production_methods/01_industry.txt

Fixed distilleries needing insane market conditions (or fruit) to be profitable.

Math is hard y'all

---

common/modifier_type_definitions/exether_modifiers_goods.txt

Game didn't know what an airship output was.

Added Airships to the mod with airships

---

common/building_groups/exether_building_groups.txt
common/buildings/exether_raw_resources.txt
common/production_method_groups/exether_raw_resources.txt
common/production_methods/exether_raw_resources.txt

this is the land-based dragon ruins building -- outputs WIP

dragon ruins building

---

common/defines/00_defines.txt

Fix major issues in define file resulting in bigly issues.

fix critical define issues

---

common/defines/00_defines.txt
common/scripted_effects/00_starting_inventions.txt
common/technology/eras/00_eras.txt
common/technology/eras/_eras.info

global tech cost reduced 10%
ahead of time penalty reduced by 20%
buffed starting tech tiers 4 & 5

make tech less painful

---

common/buildings/exether_advanced.txt
common/pop_needs/00_pop_needs.txt
common/production_method_groups/exether_advanced.txt
common/production_methods/exether_advanced.txt

Supporting Alcoholism and Shiny Object Acquisitions

---

common/production_methods/exether_misc.txt

Reduced Lodge profitability.
Raised secondary profitability of lodges.

Lick the monsters. Some are into that.

---

common/building_groups/exether_building_groups.txt
common/buildings/exether_raw_resources.txt
map_data/state_regions/02_central_zalaron.txt

This should fix the buildings trying to privatize themselves. Gonna need more play-testing.

I wish for better mining

---

common/history/buildings/00_noricum.txt
common/history/buildings/01_settler_coast.txt
common/history/buildings/02_central_zalaron.txt
common/history/buildings/03_bay_of_new_fortune.txt
common/history/buildings/04_west_zalaron.txt
common/history/buildings/06_northwestern_islands.txt

Stop trying to make wrought iron a thing.

Fixing the building files again

---

common/history/diplomacy/00_subject_relationships.txt

this little guy was sneakily hiding at the bottom

okay random curly boy at the bottom removed

---

common/buildings/exether_plantations.txt
common/country_definitions/06_northwestern_islands.txt
common/history/buildings/06_northwestern_islands.txt
common/history/countries/qar - qarinor.txt
common/history/military_formations/06_military_formations_northwestern_islands.txt
common/history/pops/06_northwestern_islands.txt
map_data/state_regions/06_northwestern_islands.txt

DIS pop stuff
QAR playability
Cold Mint/Fruit accesible now
+ More

Last minute stuff

---

common/buildings/exether_industrial.txt
common/buildings/exether_infrastructure.txt
common/buildings/exether_misc.txt
common/history/military_formations/01_military_formations_settler_coast.txt

Added background for Distilleries
Altered starting military for Darvak (added general to starting formation, renamed formation)
Added Autonomous expansion rules for:
Fur Hunting Lodges (just in case)
Roads (didn't exist beforehand)

even more chaos

---

common/buildings/exether_infrastructure.txt
common/production_method_groups/exether_infrastructure.txt
common/production_methods/exether_infrastructure.txt

Changed new files to use UTM-8 w/BOM

encoding fix of a lifetime

---

common/buildings/exether_urban.txt
common/production_method_groups/exether_urban_center.txt
common/production_methods/exether_urban.txt

initially uses ectoplasm, then thaumacores, and then godsblood(oil)

adds etherial power plant.

---

common/ideologies/exether_leader_ideologies_DIS_flavored.txt

epidemiologist is for dragonblight, but artificer baron changes are for main
kill branch after merging

epidemiologist ideology + change to artificer baron

---

localization/replace/english/exether_buildings_l_english.yml
localization/replace/english/exether_production_methods_l_english.yml

adds location
second try... hopefully will show up

Etherial Power Plants localisation

---

localization/replace/english/exether_buildings_l_english.yml
localization/replace/english/exether_production_methods_l_english.yml

Etherial Power Plants localization

---

common/history/buildings/02_central_zalaron.txt
common/history/military_formations/02_military_formations_central_zalaron.txt

Honestly very proud of this one. One of my better works I feel.

PROJECT: HIGH ELF COMPLETE

---

common/on_actions/00_code_on_actions.txt

Add the check to see if a state is coastal to the on_colony_create

---

common/history/buildings/00_noricum.txt
common/history/military_formations/00_military_formations_noricum.txt

DUMONIAAAAAAAAAAAAAAAAAAAAA
(Milformation for Dumonia)

PROJECT: DUMONIAN FIST
